project:
  type: book
  output-dir: _book
  resources:
    - webr-serviceworker.js
    - webr-worker.js
    - _headers

book:
  title: "My contribution to 30 days chart challenge"
  author: "Edo Danilyan"
  date: "2023/12/14"
  page-navigation: true
  chapters:
    - index.qmd
    - part-to-whole.qmd
    - waffle.qmd
    - fauna-flora.qmd
    - historical.qmd
    - slope.qmd
    - dataday-OWID.qmd
    - hazards.qmd
    - humans.qmd
    - high:low.qmd
    - hybrid.qmd
    - circular.qmd
    - theme-day-BBCNews.qmd
    - pop-culture.qmd
    - newtool.qmd
    - positive-negative.qmd
    - family.qmd
    - networks.qmd
    - data-day-EuroStat.qmd
    - anthropocene.qmd
    - correlation.qmd
    - down-upwards.qmd
    - green-energy.qmd
    - tiles.qmd
    - theme-dayUN-Woman.qmd
    - global-change.qmd
    - local-change.qmd
    - good-bad.qmd
    - trend.qmd
    - monochrome.qmd
    - data-day-Worldbank.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/danilyanedo7/30dayschartchallenge
  sharing: [twitter, facebook]
  navbar:
    title: ""
    logo: ""
    background: "#0b2735"
    search: true
    right:
      - text: "Home"
        file: intro.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
